### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by ghost** [Nuno135/memejs#5]
Hello,

I use this for my Discord bot and I found that it's very resource intensive and slow. Getting a meme takes around 5 to 7 seconds and uses around 35% of CPU usage (on a Raspberry Pi 4). Is there any way to speed up this process?

Here's my code:
![Screenshot from 2020-04-29 18-13-36](https://user-images.githubusercontent.com/51246620/80620080-0fba7880-8a35-11ea-9621-dbcdd3fc9bcd.png)

**Comment by ghost** [comment]
Seems like the `random-puppy` module is much faster, I think it's because it uses Imgur's API for reddit posts somehow.

**Comment by saintnuno** [comment]
Yeah, the reason it's so slow is because of the recent subreddit check function I added (It sends 2 requests). I'll fix that within the next few days.

**Comment by imposd** [comment]
If anyone comes across this issue as stated above. It will be fixed in the WIP version of memejs I am currently working on.

**Comment by MarshallAsch** [comment]
@scrap  is that performance issue also present in https://github.com/Nuno135/memejs/pull/6? I basically rewrite the entire module for that.

**Comment by imposd** [comment]
@MarshallAsch This issue should be fixed now, if you would like to contribute to the project still for future references, add me on discord Imposed#1337

**Comment by imposd** [comment]
Oh yeah also @MarshallAsch the reasoning due to slow performances, was because we were using the request library. Which is pretty slow ^ using something more "native" like http/fetch will help tremendously
